//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaJogos.ConnectionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public int idCompra { get; set; }
        public int jogos_idjogos { get; set; }
        public int clientes_idclientes { get; set; }
        public Nullable<System.DateTime> dtCompra { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<float> valor { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual jogos jogos { get; set; }
    }
}
